### ISSUE TITLE
Call for WGISD video inputs

### ISSUE THREAD

**Issue by Nikumata** [thsant/wgisd#3]
Dear authors，would you please provide the original files of the video demo？

**Comment by thsant** [comment]
The video frames are available now in the `extras` directory.

**Comment by Nikumata** [comment]
Thanks for providing the video frames! they do some help for me.  By the way, I noticed that not all images have point annotations, then, I have completed all 300 images point-level annotations for berry counting，hope these will do some help about your project. I have sent the zip file to your contact email, you can check the annotation quality and decide whether to fork them.
