### ISSUE TITLE
porting to COCO format

### ISSUE THREAD

**Issue by andreaceruti** [thsant/wgisd#7]
I have done a Python script that takes .npz mask files and produces a json file as the COCO standard, this was useful to me since I was trying to upload polygon annotations in a visualization program for annotations that requires more standard formats. 

Before creating a repo on github with just my script and the json file I would like to know how should I behave for licenses etc.?
How I should fill these json objects following COCO format?

"info": {
    "description": "",
    "url": "",
    "version": "",
    "year": x,
    "contributor": "",
    "date_created": ""
},
licenses": [
    {
        "url": "",
        "id": 1,
        "name": ""
    }
}

**Comment by thsant** [comment]
@andreaceruti , would you like to contribute your code and COCO-like annotations for the masks to WGISD official repo (this repo)? 

If you like to create an independent repo, the license (CC BY-NC 4.0) protect you, you just need to give the attribution (ie, inform a link to the original WGISD for reference).

I also not sure about how to fill the COCO format.

**Comment by andreaceruti** [comment]
@thsant I have created the repo on my profile, I hope It is ok with licenses. 

Then if you want to upload the JSON file for COCO-like annotations to the official wgisd repo feel free to do that. You can download the json file directly from [my repo](https://github.com/andreaceruti/wgisd_coco) or tell me what way do you prefer.
